# Generated by Django 5.2.3 on 2025-06-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(help_text='The host server for sending emails.', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587, help_text='The port number for the email server.')),
                ('email_host_user', models.CharField(help_text='The username for the email account.', max_length=255)),
                ('email_host_password', models.CharField(help_text='The password for the email account.', max_length=255)),
                ('email_use_tls', models.BooleanField(default=True, help_text='Use TLS for the email connection.')),
                ('email_use_ssl', models.BooleanField(default=False, help_text='Use SSL for the email connection.')),
                ('from_email', models.EmailField(help_text="The 'from' address for outgoing emails.", max_length=254)),
            ],
            options={
                'verbose_name': 'Email Settings',
                'verbose_name_plural': 'Email Settings',
            },
        ),
    ]
