# Generated by Django 5.2.3 on 2025-07-13 20:43

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_remove_emailsettings_email_host_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='AI API Key')),
                ('security_token', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True, verbose_name='Security Token')),
            ],
            options={
                'verbose_name': 'AI Security Settings',
                'verbose_name_plural': 'AI Security Settings',
            },
        ),
    ]
