# Generated by Django 5.2.3 on 2025-07-13 21:28

import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_aisecuritysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisecuritysettings',
            name='is_configured',
            field=models.BooleanField(default=False, help_text='Indicates if the connection to the AI provider has been successfully tested.'),
        ),
        migrations.AddField(
            model_name='aisecuritysettings',
            name='provider',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Google Gemini')], default='openai', help_text='The AI provider to use for security analysis.', max_length=50),
        ),
        migrations.AlterField(
            model_name='aisecuritysettings',
            name='api_key',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='API key for the selected AI provider.', null=True),
        ),
        migrations.AlterField(
            model_name='aisecuritysettings',
            name='security_token',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, help_text='Optional security token or organization ID.', null=True),
        ),
    ]
