# Generated by Django 5.2.2 on 2025-06-08 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
