# Generated by Django 5.2.2 on 2025-06-11 09:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_customuser_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A user-friendly name for the key.', max_length=255)),
                ('credential_id', models.BinaryField(max_length=512, unique=True)),
                ('public_key', models.BinaryField(max_length=512)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_keys', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
