# Generated by Django 5.2.3 on 2025-09-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_customuser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
