# Generated by Django 5.2.2 on 2025-06-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_recoverycode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='recovery_codes_verified',
            field=models.BooleanField(default=False),
        ),
    ]
