# Generated by Django 5.2.2 on 2025-06-12 09:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_customuser_recovery_codes_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
