# Generated by Django 5.2.2 on 2025-06-12 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_length', models.PositiveIntegerField(default=8, help_text='Minimum password length.')),
                ('require_uppercase', models.BooleanField(default=True, help_text='Require at least one uppercase letter.')),
                ('require_lowercase', models.BooleanField(default=True, help_text='Require at least one lowercase letter.')),
                ('require_number', models.BooleanField(default=True, help_text='Require at least one number.')),
                ('require_symbol', models.BooleanField(default=True, help_text='Require at least one special character.')),
                ('password_expiration_days', models.PositiveIntegerField(default=90, help_text='Number of days until a password expires. 0 for no expiration.')),
                ('password_history_limit', models.PositiveIntegerField(default=5, help_text='Number of old passwords to remember to prevent reuse.')),
            ],
            options={
                'verbose_name': 'Password Policy',
                'verbose_name_plural': 'Password Policies',
            },
        ),
        migrations.CreateModel(
            name='PasswordHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_hash', models.CharField(help_text='The hashed password.', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Password History',
                'verbose_name_plural': 'Password History',
                'ordering': ['-created_at'],
            },
        ),
    ]
