# Generated by Django 5.2.2 on 2025-06-12 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='passwordpolicy',
            old_name='require_number',
            new_name='digit_required',
        ),
        migrations.RenameField(
            model_name='passwordpolicy',
            old_name='password_expiration_days',
            new_name='expiry_days',
        ),
        migrations.RenameField(
            model_name='passwordpolicy',
            old_name='require_lowercase',
            new_name='lowercase_required',
        ),
        migrations.RenameField(
            model_name='passwordpolicy',
            old_name='require_symbol',
            new_name='special_char_required',
        ),
        migrations.RenameField(
            model_name='passwordpolicy',
            old_name='require_uppercase',
            new_name='uppercase_required',
        ),
        migrations.RemoveField(
            model_name='passwordpolicy',
            name='password_history_limit',
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='history_limit',
            field=models.PositiveIntegerField(default=3, help_text='Number of old passwords to remember to prevent reuse.'),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='passwordpolicy',
            name='special_characters',
            field=models.CharField(default="!@#$%^&*()_+-=[]{};':\\|,.<>/?", max_length=255),
        ),
    ]
