# Generated by Django 5.2.2 on 2025-06-09 10:40

from django.db import migrations


def create_default_types(apps, schema_editor):
    CustomerType = apps.get_model('Customers', 'CustomerType')
    default_types = ['Company', 'Individual']
    for type_name in default_types:
        CustomerType.objects.get_or_create(name=type_name)



class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_customertype_customer_customer_type'),
    ]

    operations = [
        migrations.RunPython(create_default_types, reverse_code=migrations.RunPython.noop),
    ]
