# Generated by Django 5.2.2 on 2025-06-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_create_default_customer_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delegated_person_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
