# Generated by Django 5.2.2 on 2025-06-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recaptcha_site_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_secret_key', models.CharField(blank=True, max_length=255)),
                ('recaptcha_enabled', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Security Settings',
                'verbose_name_plural': 'Security Settings',
            },
        ),
    ]
