# Generated by Django 5.2.2 on 2025-06-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_securitysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='session_expiration_hours',
            field=models.PositiveIntegerField(default=24, help_text='Number of hours before a user session expires.'),
        ),
    ]
