# Generated by Django 5.2.3 on 2025-06-17 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0003_securitysettings_session_expiration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='default_from_email',
            field=models.EmailField(blank=True, help_text="The 'from' address for outgoing emails. If blank, EMAIL_HOST_USER will be used.", max_length=254),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='email_host',
            field=models.CharField(blank=True, help_text='e.g., smtp.gmail.com', max_length=255),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='email_host_password',
            field=models.CharField(blank=True, help_text='Your email password or app password', max_length=255),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='email_host_user',
            field=models.EmailField(blank=True, help_text='Your email address', max_length=254),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='securitysettings',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
