# Generated by Django 5.2.3 on 2025-06-17 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_securitysettings_default_from_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='email_use_ssl',
            field=models.BooleanField(default=False, help_text='Use SSL for the email connection. Typically used with port 465.'),
        ),
    ]
