# Generated by Django 5.2.3 on 2025-06-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0005_securitysettings_email_use_ssl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitysettings',
            name='default_from_email',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_host',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_port',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_use_ssl',
        ),
        migrations.RemoveField(
            model_name='securitysettings',
            name='email_use_tls',
        ),
    ]
