# Generated by Cascade AI on 2025-07-15
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'security',
            '0006_remove_securitysettings_default_from_email_and_more',
        ),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityRisk',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                (
                    'check_command',
                    models.TextField(
                        help_text='Command to check for the risk condition.'
                    ),
                ),
                (
                    'match_pattern',
                    models.CharField(
                        max_length=255,
                        help_text='Pattern indicating risk presence in command output.',
                    ),
                ),
                ('fix_command', models.TextField(blank=True)),
                (
                    'risk_level',
                    models.CharField(
                        max_length=8,
                        choices=[
                            ('low', 'Low'),
                            ('medium', 'Medium'),
                            ('critical', 'Critical'),
                        ],
                        default='low',
                    ),
                ),
                (
                    'required_role',
                    models.CharField(max_length=64, default='admin'),
                ),
                ('is_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
