# Generated by Django 5.2.3 on 2025-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0007_securityrisk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securityrisk',
            options={'verbose_name': 'Security Risk', 'verbose_name_plural': 'Security Risks'},
        ),
        migrations.AddField(
            model_name='securityrisk',
            name='expect_non_zero_exit',
            field=models.BooleanField(default=False, help_text='Set to True if a non-zero exit code indicates the risk is present.'),
        ),
    ]
