# Generated by Django 5.2.3 on 2025-07-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0009_securityscan_securityrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securityscan',
            name='server',
        ),
        migrations.DeleteModel(
            name='SecurityRecommendation',
        ),
        migrations.DeleteModel(
            name='SecurityScan',
        ),
    ]
