# Generated by Django 5.2.3 on 2025-09-01 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0010_remove_securityscan_server_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitysettings',
            name='self_registration_enabled',
            field=models.BooleanField(default=False, help_text='Allow users to register themselves without admin approval.'),
        ),
    ]
