# Generated by Django 5.2.3 on 2025-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='version',
        ),
        migrations.AddField(
            model_name='application',
            name='application_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='detect_type',
            field=models.CharField(choices=[('service', 'Service'), ('path', 'Path')], default='service', max_length=10),
        ),
        migrations.AddField(
            model_name='application',
            name='service_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
