# Generated by Django 5.2.3 on 2025-07-28 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_applications', '0002_remove_application_version_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_path',
            new_name='path',
        ),
    ]
