# Generated by Django 5.2.3 on 2025-07-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server_applications', '0003_rename_application_path_application_path'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='server',
        ),
        migrations.RemoveField(
            model_name='application',
            name='status',
        ),
    ]
