# Generated by Django 5.2.3 on 2025-07-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_applications', '0004_alter_application_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='detect_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='path',
        ),
        migrations.RemoveField(
            model_name='application',
            name='service_name',
        ),
        migrations.AddField(
            model_name='application',
            name='check_command',
            field=models.CharField(blank=True, help_text="The command to run to check if the application is installed (e.g., 'command -v node' or 'systemctl is-active nginx').", max_length=512, null=True),
        ),
    ]
