# Generated by Django 5.2.3 on 2025-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_applications', '0006_application_version_command'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='version_command',
        ),
        migrations.AddField(
            model_name='application',
            name='detect_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='application',
            name='version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
