# Generated by Django 5.2.3 on 2025-07-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_applications', '0007_remove_application_version_command_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
