# Generated by Django 5.2.2 on 2025-06-09 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customers', '0006_alter_customer_first_name_alter_customer_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_ip', models.GenericIPAddressField()),
                ('ssh_root_user', models.CharField(default='root', max_length=100)),
                ('ssh_user', models.CharField(max_length=100)),
                ('ssh_password', models.CharField(max_length=255)),
                ('ssh_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='Customers.customer')),
            ],
            options={
                'verbose_name': 'Server',
                'verbose_name_plural': 'Servers',
                'ordering': ['-created_at'],
            },
        ),
    ]
