# Generated by Django 5.2.3 on 2025-07-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0003_securityscan_securityrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='securityrecommendation',
            name='solution',
            field=models.TextField(default=''),
        ),
    ]
