# Generated by Django 5.2.3 on 2025-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0005_alter_securityrecommendation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('fixed', 'Fixed'), ('ignored', 'Ignored'), ('passed', 'Passed')], default='pending', max_length=50),
        ),
    ]
