# Generated by Django 5.2.3 on 2025-07-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0006_alter_securityrecommendation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityrecommendation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('ignored', 'Ignored'), ('in_progress', 'In Progress'), ('acknowledged', 'Acknowledged')], default='pending', max_length=20),
        ),
    ]
