# Generated by Django 5.2.3 on 2025-07-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0007_alter_securityrecommendation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='cpu_threshold',
            field=models.PositiveIntegerField(default=80, help_text='CPU usage threshold percentage.'),
        ),
        migrations.AddField(
            model_name='server',
            name='disk_threshold',
            field=models.PositiveIntegerField(default=80, help_text='Disk usage threshold percentage.'),
        ),
        migrations.AddField(
            model_name='server',
            name='memory_threshold',
            field=models.PositiveIntegerField(default=80, help_text='Memory usage threshold percentage.'),
        ),
    ]
