# Generated by Django 5.2.3 on 2025-07-26 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0008_server_cpu_threshold_server_disk_threshold_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(help_text="Port or port range (e.g., '22', '80,443', '1000-2000')", max_length=255)),
                ('protocol', models.CharField(choices=[('tcp', 'TCP'), ('udp', 'UDP'), ('any', 'Any')], default='tcp', max_length=10)),
                ('source_ip', models.CharField(default='0.0.0.0/0', help_text="Source IP or CIDR (e.g., '192.168.1.1', '10.0.0.0/8')", max_length=255)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('block', 'Block')], default='allow', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firewall_rules', to='Servers.server')),
            ],
            options={
                'verbose_name': 'Firewall Rule',
                'verbose_name_plural': 'Firewall Rules',
                'ordering': ['-created_at'],
            },
        ),
    ]
