# Generated by Django 5.2.3 on 2025-07-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0009_firewallrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='firewall_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
