# Generated by Cascade for ServerCredential model
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0010_server_firewall_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ciphertext', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('encrypted_dek', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='Servers.server')),
            ],
            options={
                'verbose_name': 'Server Credential',
                'verbose_name_plural': 'Server Credentials',
                'ordering': ['-created_at'],
                'unique_together': {('server', 'username', 'ciphertext')},
            },
        ),
    ]
