# Generated by Django 5.2.3 on 2025-09-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0011_servercredential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servercredential',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
