# Generated by Cascade on 2025-09-09
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servers', '0012_alter_servercredential_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='login_using_root',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_user',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_root_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='ssh_key',
        ),
    ]
