name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      env:
        SECRET_KEY: 'a-dummy-secret-key-for-ci'
        DB_NAME: testdb
        DB_USER: testuser
        DB_PASSWORD: testpassword
        DB_HOST: localhost
        DB_PORT: 5432
      run: pytest --no-create-db ServerPilot_API/

  frontend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      working-directory: ./ServerPilot_FrontEnd
      run: npm install

    - name: Run Tests
      working-directory: ./ServerPilot_FrontEnd
      run: npm test -- --watchAll=false

    - name: Build
      working-directory: ./ServerPilot_FrontEnd
      run: npm run build
